kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-example
  labels:
    type: local
spec:
  storageClassName: stateful-set-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv-storage"