apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-getting-started-pvc
spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
  volumeName: k8s-getting-started-pv
  storageClassName: managed-csi
